### ISSUE TITLE
dataset?

### ISSUE THREAD

**Issue by andyyuan78** [parry2403/R2N2#2]
envy@ub1404envy:/media/envy/data1t/github/R2N2/RSTParser/R2N2$ python tan.py 
tan.py:6: DeprecationWarning: the sets module is deprecated
  from sets import Set
Traceback (most recent call last):
  File "tan.py", line 285, in <module>
    files = [os.path.join(path, fname) for fname in os.listdir(path) if fname.endswith('.txt')]
OSError: [Errno 2] No such file or directory: '../../../Movies//sf/out/'
envy@ub1404envy:/media/envy/data1t/github/R2N2/RSTParser/R2N2$

**Comment by andyyuan78** [comment]
after change some path and created the directory:

envy@ub1404envy:/media/envy/data1t/github/R2N2/RSTParser/R2N2$ git diff
diff --git a/RSTParser/R2N2/tan.py b/RSTParser/R2N2/tan.py
index d9fb4bf..a9095d9 100644
--- a/RSTParser/R2N2/tan.py
+++ b/RSTParser/R2N2/tan.py
@@ -281,14 +281,14 @@ def loadmodel( fname):
         print 'Load model from file: {}'.format(fname)       

 if **name** == '**main**':
-    path = "../../../Movies//sf/out/"
-    path = "../../../Movies/sf/out/"
   files = [os.path.join(path, fname) for fname in os.listdir(path) if fname.endswith('.txt')]
   tfiles = files
   # [0:5000]
   print len(tfiles)
  
   # vfiles = files[0:50] + files[950:] 
-    path = "../../../Movies//sf/outtest/"
-    path = "../../../Movies/sf/outtest/"
   files = [os.path.join(path, fname) for fname in os.listdir(path) if fname.endswith('.txt')]
   # tfiles = tfiles + files[50:950]
   vfiles = files[0:5000]
  envy@ub1404envy:/media/envy/data1t/github/R2N2/RSTParser/R2N2$ 

I got a new error:
envy@ub1404envy:/media/envy/data1t/github/R2N2/RSTParser/R2N2$ python tan.py 
tan.py:6: DeprecationWarning: the sets module is deprecated
  from sets import Set
0
0
0
0
start
[]
iter | magnitude of the gradient
0
Traceback (most recent call last):
  File "tan.py", line 354, in <module>
    lr.fit(train_mat,train_pol,test_mat,test_pol)
  File "tan.py", line 138, in fit
    k = (1.0/self.m) \* np.dot(X.T,c.T)
ZeroDivisionError: float division by zero
envy@ub1404envy:/media/envy/data1t/github/R2N2/RSTParser/R2N2$

**Comment by myy000123** [comment]
I have the same problem?Can you tell me how to deal with it?Thanks a lot!
